export const properties = [
  {
    id: 'svetly-byt-2kk-vinohrady',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=1200&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448075-cbc16bb4af8e?w=1200&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1200&q=80',
    ],
    badge: 'Na pronájem',
    badgeVariant: 'rent',
    price: '22 500 Kč',
    priceUnit: '/ měs.',
    title: 'Světlý byt 2+kk s balkonem — Vinohrady',
    location: 'Praha 2 — Vinohrady',
    locationKey: 'praha-2',
    area: '58 m²',
    areaNum: 58,
    layout: '2+kk',
    layoutKey: '2+kk',
    floor: '3. patro',
    photoCount: 14,
    type: 'rent',
    description:
      'Nabízíme k pronájmu krásný, světlý byt 2+kk s balkonem v žádané lokalitě Prahy 2 — Vinohrady. Byt se nachází ve 3. patře cihlového domu s výtahem. Dispozice zahrnuje prostorný obývací pokoj s kuchyňským koutem, ložnici, koupelnu s vanou a samostatné WC. Byt je kompletně vybavený a připravený k okamžitému nastěhování. Z balkonu je příjemný výhled do vnitrobloku. V okolí veškerá občanská vybavenost, parky a výborná dopravní dostupnost.',
    rooms: 2,
    buildingType: 'Cihlový',
    equipment: 'Plně vybavený',
    energyClass: 'C',
    availableFrom: 'Ihned',
    deposit: '45 000 Kč',
    commission: '22 500 Kč (1 měsíc)',
    utilities: '3 500 Kč / měs.',
    yearRenovated: 2022,
    features: [
      'Balkon',
      'Výtah',
      'Sklep',
      'Pračka',
      'Myčka',
      'Vestavěné skříně',
      'Dřevěné podlahy',
      'Klidná lokalita',
    ],
  },
  {
    id: 'zrekonstruovany-byt-3-1-zizkov',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448075-cbc16bb4af8e?w=1200&q=80',
    ],
    badge: 'Na prodej',
    badgeVariant: 'sale',
    price: '7 490 000 Kč',
    title: 'Zrekonstruovaný byt 3+1 — Žižkov',
    location: 'Praha 3 — Žižkov',
    locationKey: 'praha-3',
    area: '74 m²',
    areaNum: 74,
    layout: '3+1',
    layoutKey: '3+1',
    floor: '2. patro',
    photoCount: 21,
    type: 'sale',
    description:
      'Prodej kompletně zrekonstruovaného bytu 3+1 v klidné části Žižkova. Byt prošel celkovou rekonstrukcí v roce 2021 — nové rozvody, koupelna, kuchyňská linka, podlahy. Dispozice: dva samostatné pokoje, obývací pokoj, kuchyň, koupelna se sprchovým koutem a WC. Byt je ideální jako investice k pronájmu nebo pro vlastní bydlení. Cihlový dům po revitalizaci, klidná ulice s výbornou dostupností do centra.',
    rooms: 3,
    buildingType: 'Cihlový',
    equipment: 'Částečně vybavený',
    energyClass: 'D',
    availableFrom: 'Po dohodě',
    commission: 'Bez provize',
    yearRenovated: 2021,
    features: [
      'Kompletní rekonstrukce',
      'Nová koupelna',
      'Nová kuchyňská linka',
      'Sklep',
      'Plastová okna',
      'Bezpečnostní dveře',
      'Blízko metra',
      'Klidná ulice',
    ],
  },
  {
    id: 'utulny-1kk-nusle',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1200&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80',
    ],
    badge: 'Na pronájem',
    badgeVariant: 'rent',
    price: '18 000 Kč',
    priceUnit: '/ měs.',
    title: 'Útulný 1+kk v centru — Nusle, ul. Svatoslavova',
    location: 'Praha 4 — Nusle',
    locationKey: 'praha-4',
    area: '38 m²',
    areaNum: 38,
    layout: '1+kk',
    layoutKey: '1+kk',
    floor: '4. patro',
    photoCount: 9,
    type: 'rent',
    description:
      'Útulný byt 1+kk v oblíbené lokalitě Praha 4 — Nusle, ulice Svatoslavova. Byt se nachází ve 4. patře panelového domu s výtahem. Dispozice: obývací pokoj s kuchyňským koutem a ložnicí, koupelna s WC. Byt je po částečné rekonstrukci, vybavený nábytkem a spotřebiči. Ideální pro jednotlivce nebo pár. Výborná dopravní dostupnost — tramvaj i metro v docházkové vzdálenosti.',
    rooms: 1,
    buildingType: 'Panelový',
    equipment: 'Plně vybavený',
    energyClass: 'C',
    availableFrom: '1. 7. 2026',
    deposit: '36 000 Kč',
    commission: '18 000 Kč (1 měsíc)',
    utilities: '2 800 Kč / měs.',
    yearRenovated: 2023,
    features: [
      'Výtah',
      'Pračka',
      'Lednice',
      'Mikrovlnná trouba',
      'Internet v ceně',
      'Blízko MHD',
      'Obchody v okolí',
      'Klidný vnitroblok',
    ],
  },
];

export function getPropertyById(id) {
  return properties.find((p) => p.id === id);
}
